
@subdominio=idat-rest-examen


GET https://{{subdominio}}.onrender.com/datos

###
GET  https://{{subdominio}}.onrender.com/id
###

GET https://{{subdominio}}.onrender.com/nomcompleto

######CON BASE DE DATOS #####

###
POST https://{{subdominio}}.onrender.com/demo/add
Content-Type: application/x-www-form-urlencoded

name=Computacion e informatica
&creditos=2

###
DELETE https://{{subdominio}}.onrender.com/demo/del
Content-Type: application/x-www-form-urlencoded

id=2

###
GET https://{{subdominio}}.onrender.com/demo/all
